#!/usr/bin/ruby

require 'optparse'

################################################################################
# DEFINITIONS
################################################################################
OK=0
WARNING=1
CRITICAL=2
UNKNOWN=3

disk_path_oid = ".1.3.6.1.4.1.2021.9.1.2"
disk_total_oid = ".1.3.6.1.4.1.2021.9.1.6"
disk_used_oid = ".1.3.6.1.4.1.2021.9.1.8"

################################################################################
# OPTION PARSING
################################################################################
options = Hash.new
options[:host] = nil
options[:mount] = nil
options[:snmpuser] = nil
options[:authpass] = nil
options[:privpass] = nil
options[:authcrypt] = nil
options[:privcrypt] = nil
options[:warnlevel] = nil
options[:critlevel] = nil
options[:debug] = false


OptionParser.new do |opts|
	opts.banner = "Usage: "

	opts.on("-H", "--host HOST", "the host to monitor") do |v|
		options[:host] = v
	end

	opts.on("-M", "--mount DEVICE", "the mount point to monitor") do |v|
		options[:mount] = v
	end

	opts.on("-u", "--user USER", "the SNMP user") do |v|
		options[:snmpuser] = v
	end

	opts.on("-A", "--authpass PASSWD", "the authetication password") do |v|
		options[:authpass] = v
	end

	opts.on("-X", "--privpass PASSWD", "the encryption password") do |v|
		options[:privpass] = v
	end

	opts.on("-a", "--authcrypt ALGORITHM", "the authpass encryption algorithm") do |v|
		options[:authcrypt] = v
	end

	opts.on("-x", "--privcrypt ALGORITHM", "the privpass encryption algorithm") do |v|
		options[:privcrypt] = v
	end

	opts.on("-w", "--warnlevel INT", "threshold percent of disk usage to trigger warning status") do |v|
		options[:warnlevel] = v.to_f
	end

	opts.on("-c", "--critlevel INT", "threshold percent of disk usage to trigger critical status") do |v|
		options[:critlevel] = v.to_f
	end

	opts.on("-d", "--debug", "toggle debug output") do
		options[:debug] = true
	end

	opts.on_tail("-h", "--help", "Print usage information") do
		puts opts
		exit
	end
end.parse!

#verify all options have been set
empty_opts = Array.new
options.each_pair do |k,v|
        if v == nil
                empty_opts << k.to_s
        end
end

if empty_opts.length > 0
        puts "ERROR - parameters #{empty_opts.join(', ')} are not set"
        exit UNKNOWN
end

################################################################################
# LOGIC
################################################################################
#check first here that we can read info via SNMP before continuing
uptime = `snmpwalk -v 3 -u #{options[:snmpuser]} -a #{options[:authcrypt]} -A #{options[:authpass]} -l authPriv -x #{options[:privcrypt]} -X #{options[:privpass]} #{options[:host]} hrSystemUptime.0 2>/dev/null`

if options[:debug] == true
	puts "SNMP uptime response: #{uptime}"
end

if uptime.length == 0
	puts "UNKNOWN - could not get a response from SNMP"
	exit UNKNOWN
end

#find the mount point in the snmp output
findDisks = `snmpwalk -v 3 -u #{options[:snmpuser]} -a #{options[:authcrypt]} -A #{options[:authpass]} -l authPriv -x #{options[:privcrypt]} -X #{options[:privpass]} #{options[:host]} #{disk_path_oid} | egrep "STRING: #{options[:mount]}"`

if findDisks.length == 0
	puts "UNKNOWN - could not find the mount point #{options[:mount]} in SNMP output"
	exit UNKNOWN
end

#get the disk index from the snmp output
disk_index = findDisks.split('=')[0].split('::')[1].split('.')[1]

#get the kb used on the disk
kb_used = `snmpwalk -v 3 -u #{options[:snmpuser]} -a #{options[:authcrypt]} -A #{options[:authpass]} -l authPriv -x #{options[:privcrypt]} -X #{options[:privpass]} #{options[:host]} #{disk_used_oid}.#{disk_index}`.split(':')[3].to_f

if options[:debug] == true
	puts "kB used: #{kb_used}"
end

#get the total kb available on the disk
kb_total = `snmpwalk -v 3 -u #{options[:snmpuser]} -a #{options[:authcrypt]} -A #{options[:authpass]} -l authPriv -x #{options[:privcrypt]} -X #{options[:privpass]} #{options[:host]} #{disk_total_oid}.#{disk_index}`.split(':')[3].to_f

if options[:debug] == true
	puts "kB total: #{kb_total}"
end

#calculate the percentage used on disk
pct_used = ( kb_used / kb_total ) * 100


#print output and exit with rc
if pct_used >=  options[:critlevel]
	puts "CRITICAL - #{pct_used}% used on #{options[:mount]} (#{kb_used}) KB out of #{kb_total} | pct=#{pct_used} usedK=#{kb_used} totalK=#{kb_total}"
	exit CRITICAL
elsif pct_used >=  options[:warnlevel]
	puts "WARNING - #{pct_used}% used on #{options[:mount]} (#{kb_used}) KB out of #{kb_total} | pct=#{pct_used} usedK=#{kb_used} totalK=#{kb_total}"
	exit WARNING
else
	puts "OK - #{pct_used}% used on #{options[:mount]} (#{kb_used}) KB out of #{kb_total} | pct=#{pct_used} usedK=#{kb_used} totalK=#{kb_total}"
	exit OK
end

